### ISSUE TITLE
Bug: Not Working

### ISSUE THREAD

**Issue by aicynide** [arnav-kr/miniTV#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting etror

### System Info

```markdown
- OS:
```

**Comment by arnav-kr** [comment]
Could you provide more info, so that i can reproduce the issue, because it seems to work fine on my size

mention any specific error you're getting, what url you are testing on, your operating system etv

**Comment by arnav-kr** [comment]
closing as no more info provided, reopen if you are here again
